### ISSUE TITLE
Recent mode changes broke thetis

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/tsfc#103]
7fcba4d changed something in some subtle way such that coffee's optimisations are invalid for a huge swathe of thetis tests.  e.g. run py.test test/tracerEq/test_v-diffusion_mes.py in the thetis repo.

We can workaround for now by winding back.   @tj-sun what stage are we at in migration?

**Comment by tj-sun** [comment]
It's basically there (*) but need code review.  To use it we'd need to switch coffee to O0 (or Ov after coffee pr is merged).

(*) I'm doing argument factorisation unconditionally, since last week I been working on some alternatives, though I haven't seen improvements on my examples so far.

**Comment by miklos1** [comment]
If you replace the inner for loop in vanilla.flatten with yield (variable, reduce(gem.Sum, expressions)), does that help?

(Sorry I'm on phone.)

**Comment by wence-** [comment]
Seems to, thanks, was trying to figure out where to put that change in.

**Comment by wence-** [comment]
Fixed in #104.
