### ISSUE TITLE
Support for CellAvg and FacetAvg

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#107]
Moving firedrakeproject/firedrake#1020 here, to make it easier to find TSFC related TODO items.

**Comment by wence-** [comment]
Picking this up (for various other reasons).  I think UFL's approach that `CellAvg` and `FacetAvg` are terminal modifiers is wrong.

My proposed strategy:

- [ ] Remove terminal modifier property from averaging operators
- [ ] push all the pullback/restriction stuff in UFL inside them
- [ ] In tsfc, when we see an averaging operator, wrap the transformed expression in `IndexSum(expr*quadrature_weight, quadrature_indices)`

This works for `FacetAvg` on facet integrals (doesn't make sense on cell integrals) and `CellAvg` on cell integrals.  For `CellAvg` on facet integrals, we would need to do something similar to the current handling of `CellVolume`.

Questions:
-  Do we care about `CellAvg` in a facet integral (I guess long term yes)
- Should I use a different quadrature rule to the quadrature for the whole expression.  It will naturally form a separate quadrature loop (irrespective of the choice).  My thought is just to use the quadrature from the integrand as is.
