### ISSUE TITLE
Use cvxopt instead of PuLP

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#117]
Evaluate and potentially switch to using `cvxopt` instead of `PuLP`.

**Comment by tj-sun** [comment]
I've written the code to use `cvxopt` and verified the results vs `PuLP`. One problem with installation though: it seems I need to use `glpk` module inside `cvxopt` to solve ILP, which means I need to build `cvxopt` with
`export CVXOPT_BUILD_GLPK=1`
`pip install cvxopt --no-binary cvxopt`
I also need to install `libglpk-dev` package on linux.
Should we proceed?

**Comment by miklos1** [comment]
PuLP also uses the GLPK package, which is why `firedrake-install` installs it in the virtualenv. You may need to do some changes to the installation, but what you describe does not sound worse or more complicated than the current situation.

**Comment by wence-** [comment]
I think you set `CVXOPT_GLPK_LIB_DIR` and `CVXOPT_GLPK_INC_DIR` when building cvxopt.

**Comment by wence-** [comment]
I note in passing this is not as trivial as I had first thought, since cvxopt needs SuiteSparse

**Comment by miklos1** [comment]
The current version of `firedrake-install` just copies over the `glpsol` binary as "installation". If we switch to `cvxopt`, then will need to properly install the library.

**Comment by tj-sun** [comment]
Made some changes, can I push a branch to tsfc to test installation?

**Comment by wence-** [comment]
yes.

**Comment by tj-sun** [comment]
Turns out I need to install blas and lapack [http://cvxopt.org/install/#ubuntu-debian](url).
Do we want to build them from source?

**Comment by wence-** [comment]
Preferably not.

**Comment by wence-** [comment]
My suggestion for using cvxopt originally was that it doesn't require forking an external process to solve the ILP, but instead just calls out to glpk via the appropriate C bindings.  If this looks like it will be too much effort, let us not expend much work now.

**Comment by tj-sun** [comment]
Will watch this space then.
I feel the API of cvxopt is more intuitive than pulp, might be worthwhile to switch if we happen to use more features from cvxopt in the future.

**Comment by tj-sun** [comment]
It appears to me that all these libraries calls something else underneath the hood to do IP. Since we only have a very small 0-1 problem in standard form to solve, I will probably have a go in implementing our own solver ...
