### ISSUE TITLE
compile_form not idempotent

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/tsfc#12]
Consider the following:

```python
from firedrake import *
from tsfc import compile_form
m = UnitCubeMesh(1, 1, 1)
V = VectorFunctionSpace(m, 'CG', 1)
f = Function(V)

k1 = compile_form(dot(f, f)*dx)[0]
k2 = compile_form(dot(f, f)*dx)[0]

assert k1.ast.gencode() == k2.ast.gencode()
```

This is because indices that are not given a `name` are initialised with a class-based incremented `count`.  Now, the on-disk kernel caches don't actually use the generated code, so this might not matter.  It's a bit funky though.

**Comment by miklos1** [comment]
I was aware of this, but did not find it critical.

**Comment by wence-** [comment]
So it's a bit funky, because imagine I clear out the kernel cache, but not the generated code cache.  And then compile some forms in a different order.  I end up needing to compile wrapper code again.
