### ISSUE TITLE
How to determine if a modified terminal is constant on the cell?

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#15]
I'm wondering what is the right approach to determine if a given derivative of a component of an argument or coefficient is constant. Here are a few ways to do it:

1. _Sniff the numerical values in the tabulation matrix._ (Our old FFC worked this way.) This may sound risky since it is numerical, while we are supposed know this information symbolically. However, considering that we know how many digits are used to print tabulation matrices in the C source code, we could know when is a matrix columnwise constant for all practical purposes. This could also work in cases when a value is constant on the facet, but not on the cell (probably rarely matters).
2. _Use a conservative estimate of the polynomial degree._ (Our current approach in TSFC.) Unfortunately it fails in some cases. For example, an RTCF element only has degree 2 * n - 1 instead of the estimated 2 * n. (Not sure what happens for trace, restricted, broken, facet and interior elements.)
3. _Use symbolic tabulation to check for constantness._ (I experimented with this one.) Unfortunately this one fails on `TraceElement`s, since symbolic values (X, Y) are not on any facet.
4. ... ?

**Comment by colinjcotter** [comment]
Trace Elements are never constant on an element. They are constant on a facet if lowest order.

**Comment by wence-** [comment]
So does 2. work *if* you get the correct degree out?

**Comment by wence-** [comment]
3. might work once we get the `tabulate(..., entity=...)` interface change.

**Comment by miklos1** [comment]
I believe this is something FInAT should be able to tell in the future, although the API we designed between TSFC and FInAT does not support it yet.

**Comment by miklos1** [comment]
I think the answer to this question is that this problem moves to FInAT which has sufficient understanding of the finite element to do the right thing.
