### ISSUE TITLE
Add overloaded operators to GEM

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#168]
So that writing complicated GEM expressions might be more concise and easier to read and review. Relevant especially with changes like FInAT/FInAT#48 and #167.

To avoid excess, we may want to restrict ourselves initially to the basic operators `+`, `-`, `*`, `/`, and indexing.

**Comment by rckirby** [comment]
Interesting.  I also need exponentiation in a few places.
Is indexing possible to add?

**Comment by miklos1** [comment]
Yes, indexing is done through writing a `__getitem__` method.

How often is exponentiation used? If it is just a few places, then it should not hurt much to write `Power(x, y)` instead of `x**y`.

**Comment by rckirby** [comment]
Ok, great on the indexing.  That will also remove some complexity.

I square a few things, but it's usually very near the leaf nodes as opposed
to sum and product being near the roots.  So Power(blah blah, 2) isn't too
bad.

**Comment by miklos1** [comment]
It should not matter whether near the leaf nodes or not, since operator overloading would just give an alternative syntax, therefore `Power(a - b*c, 2)` should work just as much as `Power(a, 2) - Power(b, 2)`.

**Comment by rckirby** [comment]
But sums and products have a lot longer things stuffed into their
arguments, so the syntactic sugar is more helpful in that case.
