### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by tkarna** [firedrakeproject/tsfc#17]
In `tsfc/fem.py` there are two calls to something like
```python
assert numpy.allclose(table, table.mean(axis=0, keepdims=True), equal_nan=True)
```
where the `equal_nan=True` argument requires numpy-1.10 or newer. As far as I know these are the only calls in the firedrake stack that do not work with numpy-1.9.1.

This may be an issue on machines where system wide numpy is ~1.9.1 and where `pip install numpy` doesn't work (TACC Stampede in my case, I was able to compile 1.10.4 manually in the end).

I wonder if there's a 1.9.1 compatible workaround to this? Also numpy version should probably be mentioned in the requirements: Now firedrake installation goes through with numpy-1.9.1 but results in a broken system.

**Comment by miklos1** [comment]
I wouldn't be surprised if things would just work without the `equal_nan=True`, but I have to test it first.

**Comment by miklos1** [comment]
So 1 hybridisation test fails with `equal_nan=False` on this assertion. First derivative of Trace(RT1) is estimated to be constant on the cell, but yields an all NaN table which is then probably not used after the simplifications are applied. I'm tagging #15 as related.

**Comment by wence-** [comment]
How about including a backwards compat module:
```python
"""
Backwards compatibility for some functionality.
"""
import numpy
from distutils.version import StrictVersion


if StrictVersion(numpy.__version__) < StrictVersion("1.10"):
    def allclose(a, b, rtol=1e-5, atol=1e-8, equal_nan=False):
        """Wrapper around ``numpy.allclose``, which see.

        If ``equal_nan`` is ``True``, consider nan values to be equal
        in comparisons.
        """
        if not equal_nan:
            return numpy.allclose(a, b, rtol=rtol, atol=atol)
        nana = numpy.isnan(a)
        if not nana.any():
            return numpy.allclose(a, b, rtol=rtol, atol=atol)
        nanb = numpy.isnan(b)
        equal_nan = numpy.allclose(nana, nanb)
        return equal_nan and numpy.allclose(a[~nana], b[~nanb],
                                            rtol=rtol, atol=atol)
else:
     allclose = numpy.allclose
```

In any case, we should certainly bump the numpy required version.

**Comment by dorugeber** [comment]
Depending on how dangerously you want to live, you could kill line 160 of
FIAT/trace_hdiv.py, and just tabulate zeroes for derivatives instead.
There's already a commented-out check at line 102-103.

**Comment by miklos1** [comment]
Well, I believe that NaNs are there to prevent silently doing something stupid. This failure happens in an assertion, which is there to... prevent silently doing something wrong. None of these are necessary if there are no other bugs, but they are good in practice.

**Comment by wence-** [comment]
How about the approach in 26edfab31?

**Comment by miklos1** [comment]
This fixes the immediate problem quite well. Another question is how to ensure version testing in the future. That should be easy with Travis once we know what versions we want to support. What versions do we want to support?

**Comment by wence-** [comment]
1.9.0 was released september 2014.  I think that's a good oldest version.  So maybe "whatever pip install without specifying the version" and also "1.9.0"?

**Comment by miklos1** [comment]
Assuming that 1.9.0 is a good oldest version, I agree. We could have a build matrix in Travis, one installing the latest numpy, and the other the oldest version we want to support.

**Comment by wence-** [comment]
That is what I am doing now.

**Comment by wence-** [comment]
I've merged code that relaxes the requirement down to 1.9.0 (and tests both 1.9 and whatever the latest that pip installs is on travis).
