### ISSUE TITLE
Common subexpression elimination breaks complex mode

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#171]
Originally reported in firedrakeproject/firedrake#1255. Minimal failing example:
```python
from firedrake import *
import ufl

mesh = UnitSquareMesh(10,10)

x = SpatialCoordinate(mesh)

domain = SubDomainData(ufl.And(0.0 <= real(x[0]),real(x[0]) <= 1.0))
```

`real(x[0])` will be CSEd, and thus assigned to a temporary variable, however, that variable has type `double complex` so the subsequent comparison does not compile with the C compiler.

```c
  double complex  t3  = creal(creal((((((0.333333333333333) * (coords[0]))) + (((0.333333333333333) * (coords[2]))))) + (((0.333333333333333) * (coords[4])))));
  double complex  t4  = ((((t3) >= (0))) && (((t3) <= (1))) ? 1 : 0);
```

**Comment by wence-** [comment]
I suppose that the code generation pass needs to be type-aware enough to declare variables of the correct type.

**Comment by miklos1** [comment]
That would be the proper solution. A quick fix could be to generate `creal(x) OP creal(y)` instead of `x OP y` in complex mode, where `OP` is a comparison operator. Ideally, C compiler could optimise away the extra rubbish generated this way.

Another possible approach would be to hack around the inlining rules...

**Comment by miklos1** [comment]
For reference: FEniCS/ffcx#127

**Comment by wence-** [comment]
I think that 6391bbc does (at least in loopy mode) my proposed type propagation fix.
