### ISSUE TITLE
cannot generate COFFEE from <class 'gem.gem.Delta'>

### ISSUE THREAD

**Issue by mmorandi** [firedrakeproject/tsfc#182]
[demo-beam3d_ufl.zip](https://github.com/firedrakeproject/tsfc/files/2895722/demo-beam3d_ufl.zip)
The attached file, when compiled with `ffc -l dolfin -r tsfc demo-beam3d_ufl.ufl` fails because of `AssertionError: cannot generate COFFEE from <class 'gem.gem.Delta'>`, while uflacs digests it without errors.

**Comment by mmorandi** [comment]
[simpltest.zip](https://github.com/firedrakeproject/tsfc/files/2897846/simpltest.zip)
Simplified testcase, without split, obtained dropping things more or less mechanically. This testcase does not make sense from a physical point of view. However, the failed assertion is the same, and uflacs is still able to deal with it. Hope this helps.

**Comment by mmorandi** [comment]
[minimaltest.zip](https://github.com/firedrakeproject/tsfc/files/2897982/minimaltest.zip)
Further reduced (minimal?) test case. The issue seems to lie in the use of a ```MixedElement```: without it tsfc works.

**Comment by miklos1** [comment]
I'm just crystall balling here, but does the problem go away if you reduce the dimension of the vector element from 6 to 3?

Conversely, what happens if you increase `unroll_indexsum` to 6?

**Comment by mmorandi** [comment]
Good catch. Reducing the global dimension of the `MixedElement` to 3 (i.e. `dim=2` in the test case, not `dim=3`, since there is also the a scalar finite element there) allows tsfc to proceed.

The same for `unroll_indexsum` : setting it to 7 (with `dim=6` in the testcase) allows tsfc to proceed, increasing it up to 6 fires the assertion.

**Comment by wence-** [comment]
So a "cheat" way to fix it is to add `remove_delta=True` to the spectral mode `finalise_options` dict like so:

```patch
diff --git a/tsfc/spectral.py b/tsfc/spectral.py
index 3db58c4..cf237ec 100644
--- a/tsfc/spectral.py
+++ b/tsfc/spectral.py
@@ -108,7 +108,7 @@ def flatten(var_reps, index_cache):
         yield (variable, expression)
 
 
-finalise_options = dict(replace_delta=False)
+finalise_options = dict(replace_delta=True)
 
 
 def classify(argument_indices, expression):
```

But I don't have as much crystal ball as @miklos1, so I don't know what's going wrong (the spectral mode is meant to eliminate deltas). Is the problem that if the delta is inside a ListTensor we don't catch it?

**Comment by miklos1** [comment]
I was asking about the unrolling stuff, but that could mask such issues in the processing pipeline that the unusually long vectors have now uncovered.

> Is the problem that if the delta is inside a ListTensor we don't catch it?

@wence-: Yes, the Delta is trapped in a ListTensor so it is not eliminated.

A draft patch that seems to mesh the best with the existing pipeline is something like this:
```diff
diff --git a/tsfc/spectral.py b/tsfc/spectral.py
index 3db58c4..585ded5 100644
--- a/tsfc/spectral.py
+++ b/tsfc/spectral.py
@@ -112,12 +112,19 @@ finalise_options = dict(replace_delta=False)
 
 
 def classify(argument_indices, expression):
+    from gem.node import noop_recursive
+
+    @noop_recursive
+    def with_hidden_delta(node, self):
+        return any(isinstance(child, Delta) or self(child)
+                   for child in node.children)
+
     """Classifier for argument factorisation"""
     n = len(argument_indices.intersection(expression.free_indices))
     if n == 0:
         return OTHER
     elif n == 1:
-        if isinstance(expression, (Delta, Indexed)):
+        if isinstance(expression, (Delta, Indexed)) and not with_hidden_delta(expression):
             return ATOMIC
         else:
             return COMPOUND
```

Though one should really use `Memoizer` instead of `noop_recursive`, and than its state should be maintained not just inside a `classify` call, but wider outside (in `flatten` I guess...)

**Comment by wence-** [comment]
@mmorandi Does the branch in #185 fix things for you (and produce the right results)?

**Comment by mmorandi** [comment]
@wence Yes, with right results. Thank you!
