### ISSUE TITLE
Merge kernels for integrals with same integral data

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/tsfc#2]
Currently if an integral data object has multiple integrals, we emit a separate kernel for each one.  The iteration domain of these kernels is guaranteed to be the same, they are only split by their metadata (which may, for example, mean differently specified quadrature degrees).

We should figure out how to merge the kernel bodies such that we produce only one kernel.

**Comment by miklos1** [comment]
It's actually not that complicated, I think. We need to loop over the integrands when calling `fem.replace_coordinates` and `fem.process`, and then just add up the corresponding GEM expressions. And then we have to feed in more than one quadrature indices into the index orderer.
