### ISSUE TITLE
Add support for new UFL Constant

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#221]
UFL has revised its Constant node (https://bitbucket.org/fenics-project/ufl/pull-requests/116), and `ufl.Constant` no longer inherits from `ufl.Coefficient`, but directly from `ufl.Terminal`.  This means that, given a pure UFL form, TSFC has no handler for Constants.

Firedrake is unaffected, because its own `firedrake.Constant` inherits directly from `ufl.Coefficient` and not from `ufl.Constant`.  It is reasonable to also adopt the new UFL node in Firedrake at the same time when support is added to TSFC.

**Comment by connorjward** [comment]
Closing as we are about to move TSFC into Firedrake and hence do not expect TSFC to work at all with FEniCS(x). This is also quite out of date as `Constant` has been changed quite a lot in Firedrake to account for issues in parallel.
