### ISSUE TITLE
Representing indices with an unknown extent in GEM

### ISSUE THREAD

**Issue by Sohva** [firedrakeproject/tsfc#228]
How should one create an index with unknown extent in GEM (or similarly, a tensor where at least a part of the shape is unknown)? Is that even possible? I tried just leaving the index.extent as None, but that causes an error in [line  @656](https://github.com/firedrakeproject/tsfc/blob/24898235a6a55ec8a96e4fbcd5541ae8af9180e9/gem/gem.py#L656) where index.extent is being compared to 1.

@miklos1 I was told you might know?

**Comment by miklos1** [comment]
There is no such thing in GEM yet.  `gem.VariableIndex` is an index with an compile-time unknown **value** (index value known at runtime only), but currently all tensors have compile-time known shapes in GEM.

**Comment by wence-** [comment]
The `gem.Index` node is a representation of an index over a compile-time _known_ extent. As a convenience, you can make the index object without specifying an extent. When it is then first used to index an object with shape, the extent is set. Subsequent usages enforce that it is used with matching extents.

For example
```python
import gem
# Create an index object
i, = gem.indices(1)
print(i.extent)
=> None
# Variable with shape (10, )
v = gem.Variable("A", (10, ))
vi = gem.Indexed(v, (i, ))
print(i.extent)
=> 10
q = gem.Variable("q", (9, ))
qi = gem.Indexed(q, (i, ))
=> ValueError
```

**Comment by Sohva** [comment]
Thank you for the explanation!
