### ISSUE TITLE
TSFC implementation for CellCoordinate

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/tsfc#35]
There is not yet a TSFC implementation for CellCoordinate.

**Comment by miklos1** [comment]
I believe the situation with `CellCoordinate` and `FacetCoordinate` is the same as with `CellVolume` and `FacetArea`. In a cell integral, only `CellCoordinate` makes sense, while in a facet integral `FacetCoordinate` and `CellCoordinate` mean different things.

It also seems that UFL accepts all combinations of { `CellCoordinate`, `FacetCoordinate` } x { `dx`, `ds` } which isn't quite right.

**Comment by miklos1** [comment]
OK, so `FacetCoordinate` with `dx` doesn't fail immediately when constructing the form, but it does fail in UFL later when trying to compile the form.

**Comment by miklos1** [comment]
Okay, #36 and firedrakeproject/firedrake#768 are subject to review, and then this issue is fixed.
