### ISSUE TITLE
Using Conditional causes compile errors

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/tsfc#40]
I get compile errors when executing the following code:
https://gist.github.com/colinjcotter/6bf83282df31ecfaf9a239781c4200b1

using the geo file:
https://gist.github.com/colinjcotter/9d29cff712f3bfd2c610843d658341c8

**Comment by wence-** [comment]
WFM.

**Comment by miklos1** [comment]
Also works for me, closing.
