### ISSUE TITLE
Compiling interior facet integrals containing grads and normals fails for vector function spaces in mixed function spaces

### ISSUE THREAD

**Issue by colinjcotter** [firedrakeproject/tsfc#41]
See:
https://gist.github.com/colinjcotter/0011563c10e8dd7065f42c21ad2cb2dd

**Comment by dorugeber** [comment]
I don't see the BDM connection?

**Comment by colinjcotter** [comment]
Oh yes, I changed it to CG to check if it was BDM related, found it wasn't,
forgot, woke up and posted the bug. It's just mixed related.

On 29 May 2016 at 09:31, Andrew T. T. McRae <notifications@github.com>
wrote:

> I don't see the BDM connection?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firedrakeproject/tsfc/issues/41#issuecomment-222349086>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF0q8t9YEt0UMcPhiEcuRhQMI34_P-L3ks5qGU7hgaJpZM4IpPY8>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by wence-** [comment]
Try the fix-zero-mixed branch?

**Comment by colinjcotter** [comment]
Yes, it works on that branch.

On 29 May 2016 at 10:42, Lawrence Mitchell <notifications@github.com> wrote:

> Try the fix-zero-mixed branch?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firedrakeproject/tsfc/issues/41#issuecomment-222351784>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF0q8o-uwXxaV4ejeIRKvnLeK9SWAxsbks5qGV-dgaJpZM4IpPY8>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
I see. So literals are normally translated translated by `ufl2gem.Mixin`, but in this case we have a positive restricted zero, and because of the terminal modifier, we catch it as a modified terminal (which it is), but then we forgot to handle literals inside modified terminals.

**Comment by colinjcotter** [comment]
I don't quite understand why zeros were an issue here, as I didn't take a
grad of any constant fields.

--cjc

On 30 May 2016 at 14:33, Miklós Homolya <notifications@github.com> wrote:

> Closed #41 <https://github.com/firedrakeproject/tsfc/issues/41> via #42
> <https://github.com/firedrakeproject/tsfc/pull/42>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firedrakeproject/tsfc/issues/41#event-676051437>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AF0q8sPDWkBquSk747Da5zNFvbHgBE9Gks5qGuctgaJpZM4IpPY8>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916

**Comment by miklos1** [comment]
I have not checked it thoroughly, but I might be because of the coefficient splitter.

**Comment by wence-** [comment]
You took grad of the P1 guy, in a mixed space.  The way the form compilation works is that we split things apart into a list tensor of the two spaces with grad applied to the pieces and then pull out the appropriately indexed bit.  This is very similar to the problem Thomas needs to deal with with trace elements being tabulated with a gradient.

**Comment by colinjcotter** [comment]
I see, thanks for explaining.

cheers
--cjc

On 30 May 2016 at 14:51, Lawrence Mitchell <notifications@github.com> wrote:

> You took grad of the P1 guy, in a mixed space. The way the form
> compilation works is that we split things apart into a list tensor of the
> two spaces with grad applied to the pieces and then pull out the
> appropriately indexed bit. This is very similar to the problem Thomas needs
> to deal with with trace elements being tabulated with a gradient.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/firedrakeproject/tsfc/issues/41#issuecomment-222497097>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AF0q8oveChm5kcxucd96CtvpytXVJm6sks5qGutsgaJpZM4IpPY8>
> .
>



-- 
http://www.imperial.ac.uk/people/colin.cotter

www.cambridge.org/9781107663916
