### ISSUE TITLE
invalid code emitted for ufl.Not(ufl.Or(...))

### ISSUE THREAD

**Issue by blechta** [firedrakeproject/tsfc#55]
UFL code
```
element = FiniteElement("Lagrange", triangle, 2)
v = TestFunction(element)
x = SpatialCoordinate(triangle)
L = conditional(Not(Or(x[0]>1, x[0]<-1)), 1, 0)*v*dx
```

results in
```
double  t9  = (!(t7 > 1) || (t7 < -1) ? 1 : 0);
```

This is incorrect - parentheses are missing.

**Comment by miklos1** [comment]
Missing parenthesis is usually an AST printing problem, which is COFFEE's responsibility. @FabioLuporini?

**Comment by FabioLuporini** [comment]
Ugh. I wont have access to a machine to try this for a while, but it should be a trivial fix. Can u just wrap the string at line 198 in base.py with parentheses? That should make the problem disappear

**Comment by wence-** [comment]
Should be fixed, please update coffee.

**Comment by blechta** [comment]
Thanks :wink:
