### ISSUE TITLE
Can't use CellVolume in interpolation

### ISSUE THREAD

**Issue by wence-** [firedrakeproject/tsfc#60]
The firedrake interpolation code calls `fem.compile_ufl` directly.  This means it doesn't have access to the `cellvolume` callback that is set up by `driver.compile_integral`.  I see comments in this region that say "TODO: refactor!" and I think @miklos1 is thinking about pulling all the interpolation kernel generation into tsfc (so that the firedrake interface doesn't have to be touched when anything changes).

We'd like to use this in thetis though for various reasons, so noting the issue here.

**Comment by wence-** [comment]
@tkarna here's the relevant tsfc issue for cell volume interpolation.

**Comment by miklos1** [comment]
I hope it isn't urgent, since I'm not planning to work on it this week.

**Comment by wence-** [comment]
No no
