### ISSUE TITLE
Retire FIAT interface

### ISSUE THREAD

**Issue by miklos1** [firedrakeproject/tsfc#88]
TSFC uses FInAT elements for form compilation, but some elements are, in fact, FIAT elements wrapped in a compatibility layer. Once all elements are available or at least wrapped in FInAT (either in structured or unstructured form), the FIAT interface could be retired.

**Comment by miklos1** [comment]
Status update on this one:
- Since #147 TSFC falls back to UFL-to-FIAT element conversion only in a few special cases (`RestrictedElement`, and potentially `NodalEnrichedElement`).
- The FIAT interface is also used directly from Firedrake, particularly because FInAT/FInAT#21 remains unresolved.

**Comment by wence-** [comment]
With #223, TSFC only needs fiat compat for `NodalEnrichedElement`.

**Comment by miklos1** [comment]
> With #223, TSFC only needs fiat compat for `NodalEnrichedElement`.

If I remember correctly, `NodalEnrichedElement` is primarily used with Bubble stuff to construct elements that are interpolatable.  Other than TSFC, Firedrake also uses the FIAT interface directly in the interpolation code, but see also [this comment](https://github.com/firedrakeproject/tsfc/pull/218#issuecomment-675353729).
